version: "3.1"

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ./mysql-db:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - "8082:80"
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - MYSQL_USER=root
  #     - MYSQL_ROOT_PASSWORD=mypassword